CREATE TABLE IF NOT EXISTS meadows (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_id VARCHAR(64) NOT NULL,
    source_type VARCHAR(16) NOT NULL DEFAULT 'lpis',
    land_cover_code VARCHAR(64) NOT NULL,
    area_ha DOUBLE NOT NULL,
    area_m2 DOUBLE NOT NULL,
    nearest_road_m DOUBLE DEFAULT NULL,
    nearest_path_m DOUBLE DEFAULT NULL,
    nearest_water_m DOUBLE DEFAULT NULL,
    nearest_river_m DOUBLE DEFAULT NULL,
    nearest_settlement_m DOUBLE DEFAULT NULL,
    centroid_lat DOUBLE NOT NULL,
    centroid_lng DOUBLE NOT NULL,
    min_lat DOUBLE NOT NULL,
    min_lng DOUBLE NOT NULL,
    max_lat DOUBLE NOT NULL,
    max_lng DOUBLE NOT NULL,
    geom_geojson MEDIUMTEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_meadows_source_id (source_id),
    KEY idx_meadows_area_m2 (area_m2),
    KEY idx_meadows_nearest_road_m (nearest_road_m),
    KEY idx_meadows_nearest_path_m (nearest_path_m),
    KEY idx_meadows_nearest_water_m (nearest_water_m),
    KEY idx_meadows_nearest_river_m (nearest_river_m),
    KEY idx_meadows_nearest_settlement_m (nearest_settlement_m),
    KEY idx_meadows_centroid (centroid_lat, centroid_lng),
    KEY idx_meadows_bbox_lat (min_lat, max_lat),
    KEY idx_meadows_bbox_lng (min_lng, max_lng)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
